image:
  file: .gitpod.Dockerfile

tasks:
  - before: >

    init: >
      cd /workspace/qammod/mapper &&
      gp open gray2bin.sv &&
      gp open Makefile &&
      gp open test_gray2bin.py &&
      make SIM=verilator &&
      EXTRA_ARGS="--trace-fst --trace-structs" make SIM=verilator &&
      gtkwave dump.fst --rcvar 'initial_window_x 1920' --rcvar 'initial_window_y 1061' --rcvar 'do_initial_zoom_fit yes' &
    command: >
      cd /workspace/qammod/mapper ;
      history -s EXTRA_ARGS=\"--trace-fst --trace-structs\" make SIM=verilator ;
      history -s gtkwave dump.fst --rcvar \'initial_window_x 1920\' --rcvar \'initial_window_y 1061\' --rcvar \'do_initial_zoom_fit yes\' ;
      history -d 3

# NOTE: the geometry for gtkwave's fullscreen size can be found with xwininfo -root

# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080  # VNC for e.g. gtkwave
    onOpen: notify
  - port: 5900
    onOpen: ignore

#vscode:
#  extensions:
#    - mshr-h.veriloghdl@1.0.6:RPslnvyzniF7C66mxHT+Hg==
#    - vhdlwhiz.vhdl-by-vhdlwhiz@1.2.10:fJXQenGkzoZwUN/RddpuSw==
