name: ci

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build docker images
        run: docker build -t local < .devcontainer/Dockerfile
      -
        name: Run tests
        run: docker run -it -v $PWD:/srv -w/srv local pytest
