name: radiocores

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build Docker image
        run: docker build -t myapp .devcontainer

      - name: Run Black Python formatter inside Docker container
        run: docker run --rm -v ${{ github.workspace }}:/app myapp black --check /app

      - name: Run pytest inside Docker container
        run: |
          ci_env=`bash <(curl -s https://codecov.io/env)`
          docker run $ci_env -e CI=true --rm -v ${{ github.workspace }}:/app myapp pytest --cov-config=radiocores/.coveragerc --cov radiocores --cov-report=xml

      # Translate verilator coverage report to LCOV report.
      # Example: https://github.com/verilator/example-systemverilog/tree/master
      - name: Generate Verilator LCOV report
        run: |
          docker run \
            $ci_env \
            -e CI=true \
            --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            myapp \
            verilator_coverage \
              --annotate sim_build/annotated \
              --annotate-min 1 \
              --write-info sim_build/coverage.info \
              sim_build/coverage.dat

      - name: Check files
        run: ls

      - name: Publish Codecov report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml,sim_build/coverage.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
